name: aipm_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^11.0.0
  get: ^4.7.3
  google_fonts: ^8.2.0
  responsive_framework: ^1.5.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
